### PR TITLE
Patch for GIF Decoding/Encoding

### LINKED ISSUE #641: GIF images should have a palette
GIF animations should be 32-bit to handle composing multiple frames with different colormaps, but static images should be loaded as INDEX8 surfaces with a palette.

This is a regression and needs to be fixed for the 3.4.0 release.

### PR DESCRIPTION
**Pull request by LordOfXen**
Refactor GIF image processing to support palette management and transparency handling. This fixes #641 and #645.
Note that I could not reproduce the transparency issue with encoding using formats other than GIF.

### CODE REVIEW

File: src/IMG_gif.c [hunk 1]
```diff
@@ -423,45 +423,37 @@ ReadImage(SDL_IOStream * src, int len, int height, int cmapSize,
...
-            } else {
-                /* Invalid color index */
-                dst[0] = 255;
-                dst[1] = 0;
-                dst[2] = 255;
-                dst[3] = 255;
-            }
-        }
+    if (state->Gif89.transparent >= 0 && state->Gif89.transparent < cmapSize) {
+        SDL_SetSurfaceColorKey(image, 1, state->Gif89.transparent);
```
Comment (slouken) [inline src/IMG_gif.c]:
```suggestion
        SDL_SetSurfaceColorKey(image, true, state->Gif89.transparent);
```

**Comment by slouken** [comment]
Great, did you confirm that both of those issues are fixed?

**Comment by LordOfXen** [comment]
> Great, did you confirm that both of those issues are fixed?

I've run the animation test suite manually, tested with your mentioned test image, butterfly, and also tested with the previous issue that we solved by switching to RGBA, to make sure switching back to INDEX8 did not break it, I also tried to decode and encode a non-transparent GIF to make sure that also stays correct. All of them passed with no issues, and we got the expected results.

Not sure what else to test with, but right now, all those passes.
If you'd like, you can give it a try as well to make sure.

**Comment by slouken** [comment]
Great, I went ahead and merged this. Thanks!

**Comment by LordOfXen** [comment]
My pleasure!
