### PR TITLE
fix #206 (png-saving for RGB24 and palette with transparent)

### LINKED ISSUE #206: [enhancement] RGB24 and palette with transparent for PNG saving
Now `IMG_SavePNG` saves images incorrectly
Variants:
1. With palette: set transparent color to black - bad
2. RGBA32 - ok
3. Other formats: converts to RGBA32, fat for images without alpha - bad

Very strange behaviour, such poor opportunities - as my english...
Fix it, please

### PR DESCRIPTION
**Pull request by TrueCat17**
Add support for saving `tRNS chunk` (transparency for palette)
No convertion `RGB24` -> `RGBA32`, if we can just save `RGB24` (good for saving speed and file size)

Also I recommend you make small (or not) refactoring of file `IMG_png.c` in the future
For example, last 5 lines of `IMG_SavePNG_RW_libpng` or all code of `IMG_SavePNG_RW` writed in bad style

### CODE REVIEW

File: IMG_png.c [hunk 1]
```diff
@@ -513,6 +513,7 @@ static int IMG_SavePNG_RW_libpng(SDL_Surface *surface, SDL_RWops *dst, int freed
         png_structp png_ptr;
         png_infop info_ptr;
         png_colorp color_ptr = NULL;
+        uint8_t transparent_table[256];
```
Comment (sezero) [inline IMG_png.c:516]: Change `uint8_t` to SDL's own `Uint8`

**Comment by sezero** [comment]
@slouken ?

File: IMG_png.c (hunk 1 above)
Comment (TrueCat17) [reply IMG_png.c]: fixed

**Comment by sezero** [comment]
This broke build for dynamically loaded libpng. Will push the following patch shortly.
```diff
fixed build after https://github.com/libsdl-org/SDL_image/pull/209

diff --git a/IMG_png.c b/IMG_png.c
index a7a098b..7e67fab 100644
--- a/IMG_png.c
+++ b/IMG_png.c
@@ -46,8 +46,9 @@
 #if (PNG_LIBPNG_VER_MINOR < 5)
 #define LIBPNG_VERSION_12
 typedef png_bytep png_const_bytep;
 typedef png_color *png_const_colorp;
+typedef png_color_16 *png_const_color_16p;
 #endif
 #if (PNG_LIBPNG_VER_MINOR < 4)
 typedef png_structp png_const_structp;
 typedef png_infop png_const_infop;
@@ -108,8 +109,9 @@ static struct {
     void (*png_write_info) (png_structrp png_ptr, png_noconst15_inforp info_ptr);
     void (*png_set_rows) (png_noconst15_structrp png_ptr, png_inforp info_ptr, png_bytepp row_pointers);
     void (*png_write_png) (png_structrp png_ptr, png_inforp info_ptr, int transforms, png_voidp params);
     void (*png_set_PLTE) (png_structrp png_ptr, png_inforp info_ptr, png_const_colorp palette, int num_palette);
+    void (*png_set_tRNS) (png_structrp png_ptr, png_inforp info_ptr, png_const_bytep trans_alpha, int num_trans, png_const_color_16p trans_color);
 #endif
 } lib;
 
 #ifdef LOAD_PNG_DYNAMIC
@@ -162,8 +164,9 @@ int IMG_InitPNG()
         FUNCTION_LOADER(png_write_info, void (*) (png_structrp png_ptr, png_noconst15_inforp info_ptr))
         FUNCTION_LOADER(png_set_rows, void (*) (png_noconst15_structrp png_ptr, png_inforp info_ptr, png_bytepp row_pointers))
         FUNCTION_LOADER(png_write_png, void (*) (png_structrp png_ptr, png_inforp info_ptr, int transforms, png_voidp params))
         FUNCTION_LOADER(png_set_PLTE, void (*) (png_structrp png_ptr, png_inforp info_ptr, png_const_colorp palette, int num_palette))
+        FUNCTION_LOADER(png_set_tRNS, void (*) (png_structrp png_ptr, png_inforp info_ptr, png_const_bytep trans_alpha, int num_trans, png_const_color_16p trans_color))
 #endif
     }
     ++lib.loaded;
 
@@ -570,9 +573,9 @@ static int IMG_SavePNG_RW_libpng(SDL_Surface *surface, SDL_RWops *dst, int freed
             if (last_transparent >= 0) {
                 for (i = 0; i <= last_transparent; ++i) {
                     transparent_table[i] = palette->colors[i].a;
                 }
-                png_set_tRNS(png_ptr, info_ptr, transparent_table, last_transparent + 1, NULL);
+                lib.png_set_tRNS(png_ptr, info_ptr, transparent_table, last_transparent + 1, NULL);
             }
         }
         else if (surface->format->format == SDL_PIXELFORMAT_RGB24) {
             png_color_type = PNG_COLOR_TYPE_RGB;
```
